/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkTtdRouteImport } from './routes/work.ttd'
import { Route as WorkBillingRouteImport } from './routes/work.billing'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTtdRoute = WorkTtdRouteImport.update({
  id: '/work/ttd',
  path: '/work/ttd',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBillingRoute = WorkBillingRouteImport.update({
  id: '/work/billing',
  path: '/work/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/billing': typeof WorkBillingRoute
  '/work/ttd': typeof WorkTtdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/billing': typeof WorkBillingRoute
  '/work/ttd': typeof WorkTtdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/billing': typeof WorkBillingRoute
  '/work/ttd': typeof WorkTtdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/work/billing' | '/work/ttd'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/work/billing' | '/work/ttd'
  id: '__root__' | '/' | '/about' | '/contact' | '/work/billing' | '/work/ttd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WorkBillingRoute: typeof WorkBillingRoute
  WorkTtdRoute: typeof WorkTtdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/ttd': {
      id: '/work/ttd'
      path: '/work/ttd'
      fullPath: '/work/ttd'
      preLoaderRoute: typeof WorkTtdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/billing': {
      id: '/work/billing'
      path: '/work/billing'
      fullPath: '/work/billing'
      preLoaderRoute: typeof WorkBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WorkBillingRoute: WorkBillingRoute,
  WorkTtdRoute: WorkTtdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
